// A deterministic provider protocol fixture. Never used by the production compose file.
import http from "node:http";
async function respond(req, res) {
  if (
    req.url !== "/v1/responses" ||
    req.headers.authorization !== "Bearer fixture-not-a-real-provider-key"
  ) {
    res.writeHead(401);
    return res.end("{}");
  }
  const chunks = [];
  for await (const c of req) chunks.push(c);
  const data = JSON.parse(Buffer.concat(chunks)),
    prompt = data.input[0].content;
  if (
    data.store !== false ||
    !data.include?.includes("reasoning.encrypted_content") ||
    data.parallel_tool_calls !== false
  ) {
    res.writeHead(400);
    return res.end("{}");
  }
  if (prompt.includes("[FAIL]")) {
    res.writeHead(429);
    return res.end(JSON.stringify({ error: "A fixture provider rejection" }));
  }
  if (prompt.includes("[CONCURRENT]"))
    await new Promise((r) => setTimeout(r, 250));
  if (prompt.includes("[SLOW]")) await new Promise((r) => setTimeout(r, 30000));
  if (prompt.includes("[INCOMPLETE]")) {
    res.setHeader("content-type", "application/json");
    return res.end(
      JSON.stringify({
        status: "incomplete",
        output: [],
        usage: { input_tokens: 2, output_tokens: 3 },
      }),
    );
  }
  const results = data.input.filter((i) => i.type === "function_call_output");
  const message = (text) => ({
    type: "message",
    role: "assistant",
    content: [{ type: "output_text", text }],
  });
  const call = (name, args) => ({
    type: "function_call",
    call_id: `call_${results.length}`,
    name,
    arguments: JSON.stringify(args),
  });
  let output;
  if (prompt.includes("[LOOP]"))
    output = [call("calculate", { expression: "1+1" })];
  else if (prompt.includes("[DENIED]"))
    output = results.length
      ? [message("Unsupported tool rejected.")]
      : [call("run_shell", { command: "echo unsafe" })];
  else if (prompt.includes("[PLAIN]"))
    output = [message("A saved fixture response for a plain task.")];
  else if (!results.length) output = [call("list_documents", {})];
  else if (results.length === 1) {
    const docs = JSON.parse(results[0].output).documents;
    output = docs.length
      ? [call("read_document", { id: docs[0].id })]
      : [call("calculate", { expression: "(12 + 8) * 3" })];
  } else if (results.length === 2)
    output = [
      call("create_artifact", {
        name: "launch-checklist.txt",
        content:
          "Launch checklist\n\n1. Verify the worker.\n2. Review task results.\n3. Rehearse a backup restore.\n\nCreated by the deterministic acceptance-test fixture.",
      }),
    ];
  else
    output = [
      message(
        "Your launch checklist is ready.\n\nI reviewed the workspace context and saved a text artifact with three concrete checks: verify the worker, review results, and rehearse recovery.\n\nThis response was generated by the local acceptance-test provider fixture.",
      ),
    ];
  res.setHeader("content-type", "application/json");
  res.end(
    JSON.stringify({
      status: "completed",
      output,
      usage: { input_tokens: 40, output_tokens: 25 },
    }),
  );
}
const server = http.createServer((req, res) => {
  // Abrupt worker termination can interrupt the HTTP request body itself.
  // The fixture must survive that just as a real provider endpoint would.
  respond(req, res).catch((error) => {
    if (req.aborted || res.destroyed) return;
    console.error("Fixture rejected a request:", error.name);
    if (!res.headersSent) res.writeHead(400);
    res.end("{}");
  });
});
server.listen(8081, "0.0.0.0");
